# Stage 1: Build the Django application
FROM python:3.11 as django-build

# Set the working directory in the container
WORKDIR /app

# Copy the Django application code to the container
COPY ./customer /app

# Install dependencies using Poetry
RUN pip install poetry
RUN poetry config virtualenvs.create false
COPY poetry.lock .
COPY pyproject.toml .
RUN poetry install --no-root --no-dev

# Stage 2: Build the Node.js application
FROM node:14 as node-build

# Set the working directory in the container
WORKDIR /app

# Copy the Node.js application code to the container
COPY ./Marketer /app

# Install dependencies and build the Node.js application
RUN npm ci && npm run build

# Stage 3: Create the final runtime image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the built Django application from the previous stage to the container
COPY --from=django-build /app /app

# Copy the built Node.js application from the previous stage to the container
COPY --from=node-build /app/dist /app/static

# Expose the necessary ports for Django and Node.js applications
EXPOSE 8000 3000

# Start the Django application
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
